name: GenModWorld
main: com.github.calenria.genmodworld.GenModWorld
version: 0.1
website: https://github.com/Calenria/GenModWorld
author: Calenria
description: GenModWorld!
database: false
depend: [Vault, WorldEdit]